### ISSUE TITLE
main.py中一处bug

### ISSUE THREAD

**Issue by coffeehb** [Tr3jer/AutoHookSpider#1]
嗨，大牛，我在使用的时候发现main.py的95行处发现一个bug

self.entrances = random.sample(self.hooks,self.thread_cnt)
线程数默认设置为20，如果默认情况下使用时hooks.txt目标数小于20，或者用-t设置线程数，但大于hooks.txt里目标数时，这一行代码就会报错。

我的解决办法：在95行上面加2行代码：
'''
			if len(self.hooks) < self.thread_cnt:
				self.thread_cnt = len(self.hooks)
'''

**Comment by Tr3jer** [comment]
感谢反馈，因为是从我本地拆分出来的所以没考虑这个，域名少的改下thread_cnt就可以了。
