### ISSUE TITLE
没有inesrt，只有一大堆200而后程序结束

### ISSUE THREAD

**Issue by tetsaicn** [Tr3jer/AutoHookSpider#4]
平台为debian，数据库绝对正确，sock也换了，只有一大堆[200]doamin.com

**Comment by Tr3jer** [comment]
问题太简单，调试pymysql是否能插入数据。

**Comment by tetsaicn** [comment]
好的伐，我把try去掉看看错误信息，那个啥不应该直接pass吧，要error一下吧
